### ISSUE TITLE
Questions about parameter settings of myLusgsFoam

### ISSUE THREAD

**Issue by lpz456** [furstj/myFoam#12]
Hello professor Furstj,
        Thanks for professor's last reply. Through the nonuniform List<scalar> b.c. taht you suggested, the inlet nonuniform total pressure distribution has been successfully implemented in a 3-D high-subsonic compressor cascade. Today, there are several solver setting issues that need your help, due to I am not special in numerical algorithms.
        1. I have no idea what the term "internalIterations" refer to in the fvSolution file?  Is this the number of Gauss-Seidel sweeps or the maximum number of iterations per physical time step?
        2. I want to know whether the "MaInf 0.2" parameter under the "AUSMplusUpfluxCoeffs" dictionary in the fvscheme file has an impact on the calculation results and whether it needs to be adapted according to the inlet Mach number, i.e. "MaInf 0.6"?
        3. Is there any experience to share regarding the selection of items "hllcFlux", "betaFlux" and "AUSMplus UpFlux"? I.e., depending on the Mach number range?
        4. In my current high-subsonic compressor cascade, the steady calculations based on SST turbulence model show a little unsteadiness. Whether the results can be further converges through modifying the "dbnsFlux" term, i. e. from "AUSMplusUpFlux" to "hllcFlux", and other measures?  Or is the transient calculation required?

Looking forward to professor's help!

**Comment by lpz456** [comment]
Hello Prof,
Recently, I read your paper - "Development of a coupled matrix-free LU-SGS solver for turbulent compressible flows". I have already know that the term "internalIterations" refers to the maximum number of iterations in each time step;
In  the test of a 2-D cascade case, it is shown that "MaInf 0.2" parameter has no effect on the calculation results;
The main problem at present is the slight unsteadiness in 3-D steady calculations, although very weak.  I have no idea how to modify this situation. Next, I will try to improve the convergence of steady calculation by changing the "dbnsFlux" item, or adopt transient calculation.
Thanks!

**Comment by furstj** [comment]
Hi,

1) "internalIterations" is indeed the maximal number of non-linear iteration per time step. It is used in the case of transient simulations. Typically, one uses 1 internal iteration for steady state problems and a combination of more internal iterations with prescribed tolerances for transient case.

2) MaInf is a parameter of AUSM+up scheme which serves for low Mach preconditioning. Roughly speaking, if the local Mach number is less then MaInf, then the scheme uses partical formulas for stabilization terms. More details can be found in the original articles on AUSM+up. In general, the value MaInf=0.2 is quite universal choice.

3) The choice of dbnsFlux depends slightly on the problem you are solving. The "silver bullet" is the hllcLMFlux (it is a HLLC scheme with low Mach correction) which is able to work in wide range of Mach numbers. Personally I use hllcLM practically for all my calculations.

4) The unsteadiness can be there due to several reasons. Sometimes, it can be caused by wrong choice of inlet parameters of turbulence, sometimes by bad mesh (too coarse, high skewnes, or even too fine with y+ << 1), or by the choice of limiters for reconstruction. The problem can be also unsteady due to physical reason (compressor surging, ...). Under my experiences, the change of dbnsFlux usually does not help much.

**Comment by lpz456** [comment]
Thanks for prof's reply,
The unsteadiness is due to the y+ <<1 or not. Because the y+ is approximately 1 calculated by FLUNET or NUMECA, while approximately 0.003 calculated by OpenFOAM with the same mesh and the magnitude of wall shear stress. I think there may be some problems with yPlus calculated by OpenFOAM.

**Comment by furstj** [comment]
Hi, I have never seen such difference in y+ between Fluent and OpenFOAM (and manual calculation too)! What is your setup of wall boundary conditions for k, omega, and nut?

**Comment by lpz456** [comment]
Hello Prof,
I just learned how to upload files through GitHub. I have put the relevant case in my repositories-https://github.com/lpz456/myLusgsFoam-Tutorials
I think the wall boundary conditions for k, omega, and nut are right. But the y+ is only 0.03 through the built-in yPlus post-processing function of OpenFOAM.

**Comment by furstj** [comment]
The kqRWallFunction (b.c. for k) is suitable for high-Reynolds strategy (i.e. y+ > 50). Try to re-run your calculation with following set of wall boundary conditions (if your mesh is fine enough):

k -> kLowReWallFunction
nut -> nutLowReWallFunction
omega -> omegaWallFunction

There is quite good description of wall functions in [http://www.tfd.chalmers.se/~hani/kurser/OS_CFD_2016/FangqingLiu/openfoamFinal.pdf](http://www.tfd.chalmers.se/~hani/kurser/OS_CFD_2016/FangqingLiu/openfoamFinal.pdf)

**Comment by furstj** [comment]
I've run the calculation with your original setup and with boundary conditions from my last post. In both cases the yPlus shows very similar results:

min ~ 0.05, max ~ 3.47, average ~ 0.72

How did you find the value y+ = 0.03? The average y+ is 0.72 which seems to be fine.

**Comment by lpz456** [comment]
Thanks Prof,
Using OpenFOAMv2106, the results with my original setup: 
y+ : min = 0.0036271105, max = 1.1461074, average = 0.081571558,

while with your suggestion, the result is much more reasonable: 
y+ : min = 0.051510734, max = 3.502789, average = 0.74437461.

**Comment by furstj** [comment]
I see. There was a change between OFv2116 and OFv2112. New implementation of nutkWallFunction is able to work with also in low-Re regime. Therefore it gives (almost) correct values of nut and y+. Nevertheless, the kqRWallFunction is still only for high-Re setups (k should be 0 at the boundary which is not the case of kqrWallFunction). Therefore, my setup is correct for low-Re, yours is for high-Re :).

**Comment by lpz456** [comment]
Thanks for professor's reply!
